### ISSUE TITLE
Random Items are getting custom names, is there a way to stop this?

### ISSUE THREAD

**Issue by mjmanning25** [zizmax/AcuteLoot#1]
![image](https://user-images.githubusercontent.com/53459928/88456031-877e2f00-cece-11ea-8eed-86569ded8f4b.png)

Currently I cannot find a way to disable this behavior  and only apply the unique names to a specific item group, eg: weapons & armors.

I know this probably is intended plugin behaviour, as there are not config settings to change in this regard. But any advice would be appreciated :)

Thanks for a fun plugin!

**Comment by zizmax** [comment]
I'm glad you're enjoying the plugin!

Though I'm not entirely sure what you're asking. You want fishing/chests/the "new" command to be able to create items without unique names and rarities? This would kind of defeat the purpose of the plugin because the items would no longer be AcuteLoot and would instead be just normal items.

**Comment by mjmanning25** [comment]
Thanks for the quick reply!

Sorry I might have phrased what I meant poorly. 

I was wondering if it would be possible to only generate AcuteLoot items for a configurable category of items - for example: only generate AcuteLoot Weapons and Armor, but exclude things such as Foods and Plants from becoming AcuteLoot Items

**Comment by zizmax** [comment]
Yes actually! In the AcuteLoot folder in /plugins there is a file called materials.txt. Those make up the list of MC items that the  generator chooses from when creating random AcuteLoot. You can just remove everything in there except for the weapons and armor that you want.
