### ISSUE TITLE
The chests are filled with new items with each opening to infinity

### ISSUE THREAD

**Issue by valenvaio** [zizmax/AcuteLoot#21]
The chests are filled with new items with each opening to infinity. At 65% probability the chest is full in 3 openings. 
There is no delay for the generation of things. Experience for the opening of the chest and the generation of items is not removed.

**Comment by zizmax** [comment]
Hey @valenvaio, thanks for reaching out. Can you provide some more detail about the context of the issue you are facing?

- Was this a vanilla (naturally generated) chest, or a chest you placed and configured with the /al chest command? If it was the command, what exact command did you run?
- What do you mean by "experience for the opening of the chest?" Currently AcuteLoot does not modify experience levels when opening chests.

**Comment by valenvaio** [comment]
- It was a vanilla chest. Naturally generated. In the fortress of hell.
- Yeah, he doesn't do that. That was an assumption.

**Comment by zizmax** [comment]
Hmm, this is sounding a bit like another issue (#3) that was never resolved due to lack of documentation and being unable to reproduce it. Check it out [here](https://github.com/zizmax/AcuteLoot/issues/3). Does that match what you've been seeing?

- Do you have any other plugins that could potentially modify chest behavior?
- Which version of AcuteLoot and which server software and version?
- Did it only occur once, or have you seen it occur multiple times?
- Any other details you could provide about the context, timing, or situation?

As I said in the other issue, I've performed extensive testing and code review related to this issue and haven't been able to reproduce it. Without knowing anything more, it's almost impossible to diagnose/fix. If you could provide a video of it happening, that may prove very helpful.

**Comment by valenvaio** [comment]
Not fully consistent. In my case, every time I open the chest, it is filled with several new items that the plugin generates. The parameter of the probability of appearance of items is taken into account. Because if the probability is greater, things appear more often, at every opening. If the probability is less, then things do not appear at every opening.

There are no other plugins affecting the chest. I can check the work on an empty server.  Since there are many plugins on the server.

latest releases https://purpur.pl3x.net/downloads/#1.16.5

It happens all the time

**Comment by zizmax** [comment]
This issue is really bugging me, because I've literally never been able to reproduce it myself. I just now tried replicating it. 

Brand new purpur server, latest version of AcuteLoot, no other plugins, and opening chests multiple times in Nether Fortress. 

As expected, AcuteLoot only generated once, despite opening the chest multiple times. Here's a [recording ](https://imgur.com/a/tNQ8TL9)of the test.

**Comment by lazerl0rd** [comment]
@zizmax, I've noticed that the conflict seems to be with Paper's `lootables.auto-replenish` feature. AcuteLoot doesn't respect the `restrict-player-reloot` flag and the chests end up "reloot-ing" multiple times regardless of the flag.

**Comment by zizmax** [comment]
@lazerl0rd Wow, I think this may be exactly the problem. I haven't been able to do specific testing yet, but I think you're right. This totally makes sense and I'll be doing testing and will work on patching it in an upcoming release. Thanks!

**Comment by zizmax** [comment]
@lazerl0rd @valenvaio v2.1.12 should hopefully fix this issue! Please let me know if you run into any other problems.

**Comment by lazerl0rd** [comment]
> @lazerl0rd @valenvaio v2.1.12 should hopefully fix this issue! Please let me know if you run into any other problems.

I'll test it out tomorrow.
