### ISSUE TITLE
Loot not spawning in structures generated by plugins like Custom Structures and Oh The Dungeons You'll Go.

### ISSUE THREAD

**Issue by browloga490** [zizmax/AcuteLoot#5]
I am currently using the plugins, Custom Structures (https://www.spigotmc.org/resources/custom-structures.38249/) and Oh The Dungeons You'll Go (https://www.spigotmc.org/resources/oh-the-dungeons-youll-go.76437/). For some reason, the chests within these generated structures do not contain any of the Acute Loot items. What qualifies as a naturally spawned chest, and is there a way to fix this?

**Comment by zizmax** [comment]
Hi @browloga490, this is a great question. At a technical level, AcuteLoot is checking chests to see if they have a valid lootTable. Chests spawned by the vanilla world generator have [lootTables](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/loot/LootTable.html). Conveniently, the lootTable is removed as soon as the chest is opened for the first time. In this way, the lootTable is a good proxy for an "unopened, naturally spawned" chest. It appears that the plugins above don't give their chests lootTables through the Spigot/Bukkit API which would explain why they are ignored by AcuteLoot.

As the plugin was originally designed to work in a relatively vanilla manner, we never considered handling it in any other way. I think it is worth at least looking into alternatives so that plugins like the ones you're running can work with AcuteLoot's generators. However it will require some thought and testing to design a system that works in the most general cases and maintains effortless compatibility with the vanilla game.

**Comment by browloga490** [comment]
Sorry for the late replay. Thank you for the explanation!

**Comment by zizmax** [comment]
@browloga490 Just wanted to let you know, the latest update includes a command to designate AcuteLoot chests. You can also make them auto-refilling over time. I know this won't help with automatically creating new chests in new chunks, but hopefully you can still find it useful! Hop in the Discord if you have any questions or other ideas.
